### ISSUE TITLE
IP is not allowed to access Lemon Way's API

### ISSUE THREAD

**Issue by TimDorand** [lemonwaysas/php-client-directkit-xml#10]
When I upload my project online, I can't access to the API for RegisterWallet or any other functions.
Even though my IP is whitelisted. Is there a "production environnement" that disable the api online for the sandbox ?

**Comment by pham-dat** [comment]
What did you have as error?

**Comment by TimDorand** [comment]
I had an error because my server wasn’t whitelisted ! Its fine now, thank you

**Comment by Kirankushwah** [comment]
have been trying to contact lemonway support but no one responded to me. I am having difficulty understanding how to integrate lemonway into a website. So what I did is I created an access_token then I tried to create a payment form using Rest API by curl but I got 403 error Forbidden: Access is denied. I don't know if what I am doing is right or wrong can any one help me. i have tried on local
