### ISSUE TITLE
GetMoneyInTransDetails : CardType is not returned

### ISSUE THREAD

**Issue by Guinome** [lemonwaysas/php-client-directkit-xml#25]
Hi,

I wan't to save the authNumber, cardNumber & cardType when an order is success.
```php
$LWapi = $this->container->get('lemonway_sdk.api');
$res = $LWapi->GetMoneyInTransDetails(array('somearguments'));
//check for errors
...
$current = $res->operations[0];
if ((string)$current->STATUS == Operation::STATUS_SUCCES) {
    $order->setAuthNumber($current->EXTRA->AUTH)
          ->setCardNumber($current->EXTRA->NUM)
          ->setCardType($current->EXTRA->TYPE);
    $em->persist($order);
}
$entityManager->flush();
```
The authNumber and CardNumber is well saved, but the `$current->EXTRA->TYPE` is an empty string.

Any clue ?

**Comment by pham-dat** [comment]
Actually, it has to be EXTRA->TYP instead of TYPE.
Thank you. We updated the SDK.

**Comment by duongphuhiep** [comment]
hi,

it is a little bit out of subject, but just for information

we recommend our new partners to use directkitjson2 instead.

https://github.com/lemonwaysas/php-client-directkit-json2

it will simplify your codes, enhance the network traffic, and keep you away from bugs like this one.

Anyway we keep support, and fix the SDK for old customers.

kind regards
